LabBigSchool_VoThanhHuy/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LabBigSchool_VoThanhHuy.Models
{
    public class Course
    {
        public int Id { get; set; }
        public bool IsCanceled { get; set; }
        public ApplicationUser Lecturer { get; set; }
        [Required]
        public string LecturerId { get; set; }

        [Required]
        [StringLength(255)]
        public string Place { get; set; }
        public DateTime DateTime { get; set; }
        public Category category { get; set; }
        [Required]
        public byte CategoryID { get; set; }
    }
}

LabBigSchool_VoThanhHuy/ViewModels/CourseViewModel.cs
using LabBigSchool_VoThanhHuy.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LabBigSchool_VoThanhHuy.ViewModels
{
    public class CourseViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Place { get; set; }

        [Required]
        [FutureDate]
        public string Date { get; set; }

        [Required]
        [ValidTime]
        public string Time { get; set; }
        public byte Category { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public string Heading { get; set; }
        public string Action
        {
            get { return (Id != 0) ? "Update" : "Create"; }
        }
        public DateTime GetDateTime()
        {
            return DateTime.Parse(string.Format("{0} {1}", Date, Time));
        }
    }
}

LabBigSchool_VoThanhHuy/ViewModels/CoursesViewModel.cs
using LabBigSchool_VoThanhHuy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LabBigSchool_VoThanhHuy.ViewModels
{
    public class CoursesViewModel
    {
        public IEnumerable<Course> UpcommingCourses { get; set; }
        public bool ShowAction { get; set; }
    }
}

LabBigSchool_VoThanhHuy/Controllers/CoursesController.cs
using LabBigSchool_VoThanhHuy.Models;
using LabBigSchool_VoThanhHuy.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabBigSchool_VoThanhHuy.Controllers
{
    public class CoursesController : Controller
    {
        // GET: Courses
        private readonly ApplicationDbContext _dbContext;
        public CoursesController()
        {
            _dbContext = new ApplicationDbContext();
            
        }
        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new CourseViewModel
            {
                Categories = _dbContext.Categories.ToList(),
                Heading = "Add Course"

            };
            return View("CourseForm",viewModel);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _dbContext.Categories.ToList();
                return View("CourseForm", viewModel);
            }
            var course = new Course
            {
                LecturerId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                CategoryID = viewModel.Category,
                Place = viewModel.Place,
            };
            _dbContext.Courses.Add(course);
            _dbContext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        [Authorize]
        public ActionResult Attending()
        {
            var userId = User.Identity.GetUserId();

            var courses = _dbContext.Attendances
                .Where(a => a.AttendeeId == userId)
                .Select(a => a.Course)
                .Include(l => l.Lecturer)
                .Include(l => l.category)
                .ToList();

            var viewModel = new CoursesViewModel
            {
                UpcommingCourses = courses,
                ShowAction = User.Identity.IsAuthenticated
            };
            return View(viewModel);

        }
        [Authorize]
        public ActionResult Mine()
        {
            var userId = User.Identity.GetUserId();

            var courses = _dbContext.Courses
                .Where(c => c.LecturerId == userId && c.DateTime > DateTime.Now)

                .Include(l => l.Lecturer)
                .Include(l => l.category)
                .ToList();


            return View(courses);

        }
        [Authorize]
        public ActionResult Edit(int id)
        {
            var userId = User.Identity.GetUserId();

            var courses = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);
            var viewModel = new CourseViewModel
            {
                Categories = _dbContext.Categories.ToList(),
                Date = courses.DateTime.ToString("dd/M/yyyy"),
                Time = courses.DateTime.ToString("HH:mm"),
                Category = courses.CategoryID,
                Place = courses.Place,
                Heading = "Edit Course",
                Id = courses.Id,

            };
            return View("CoursesForm", viewModel);

        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(CourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _dbContext.Categories.ToList();
                return View("CoursesForm", viewModel);
            }
            var userId = User.Identity.GetUserId();

            var courses = _dbContext.Courses.Single(c => c.Id == viewModel.Id && c.LecturerId == userId);
            courses.Place = viewModel.Place;
            courses.DateTime = viewModel.GetDateTime();
            courses.CategoryID = viewModel.Category;

            _dbContext.SaveChanges();

            return RedirectToAction("Index", "Home");

        }
    }
}

LabBigSchool_VoThanhHuy/Views/Courses/Attending.cshtml
@model LabBigSchool_VoThanhHuy.ViewModels.CoursesViewModel
@{
    ViewBag.Title = "Attending";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Attending</h2>
<ul class="course">
    @foreach (var course in Model.UpcommingCourses)
    {
        <li>
            <div class="date">
                <div class="month">
                    @course.DateTime.ToString("MM")
                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")
                </div>
            </div>
            <div class="details">
                <span class="lecturer">

                    @course.Lecturer.Name
                    @if (course.IsCanceled)
                    {
                        <span class="label label-warning"> Canceled</span>
                    }

                    @if (Model.ShowAction && !course.IsCanceled)
                    {

                        <button class="btn btn-link btn-sm js-toggle-follow" data-user-id="@course.LecturerId">Follow</button>

                    }
                    <br />
                </span>

                <span class="caterogy">
                    @course.category.Name
                </span>
            </div>
        </li>
    }
</ul>
@section scripts{
    <script>
        $(document).ready(function () {
            $(".js-toggle-attendance").click(function (e) {
                var button = $(e.target);
                $.post("/api/attendances", { courseId: button.attr("data-course-id") })
                    .done(function () {
                        button
                            .removeClass("btn-default")
                            .addClass("btn-info")
                            .text("Going");
                    })
                    .fail(function () {
                        alert("Something failed!");
                    });
            });
            $(".js-toggle-follow").click(function (e) {
                var button = $(e.target);
                $.post("/api/followings", { followeeId: button.attr("data-user-id") })
                    .done(function () {
                        button.text("Following");
                    })
                    .fail(function () {
                        alert("Something failed");
                    });
            });
        });
    </script>
}

LabBigSchool_VoThanhHuy/Views/Courses/CourseForm.cshtml
@model LabBigSchool_VoThanhHuy.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
@*<div class="row"></div>*@
@using (Html.BeginForm(Model.Action, "Courses"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Place)
        @Html.TextBoxFor(m => m.Place, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Place)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Date)

    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Time)
        @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Time)

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Category)
        @Html.DropDownListFor(m => m.Category, new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Category)

    </div>

    <button type="submit" value="Save" class="btn btn-primary"> Save</button>
}
@section scripts
     {
    @Scripts.Render("~/bundless/jquereval");
}

LabBigSchool_VoThanhHuy/Views/Courses/Mine.cshtml
@model IEnumerable<LabBigSchool_VoThanhHuy.Models.Course>
@{
    ViewBag.Title = "Mine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mine</h2>
<ul class="course">
    @foreach (var course in Model)
    {
        <li>
            <div class="date">
                <div class="month">
                    @course.DateTime.ToString("MM")
                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")
                </div>
            </div>
            <div class="details">
                <span class="lecturer">

                    @course.Lecturer.Name

                    <br />
                </span>

                <span class="caterogy">
                    @course.category.Name
                </span>
            </div>

            <div class="action">
                <a href="@Url.Action("Edit","Courses", new {id = course.Id})"> Edit &nbsp;</a> |
                <a href="#" class="js-cancel-course" data-course-id="@course.Id"> Cancel</a>
            </div>
        </li>
    }

</ul>
@section scripts{
    <script>
        $(document).ready(function () {
            $(".js-cancel-course").click(function (e) {
                e.preventDefault();
                var link = $(e.target);
                bootbox.confirm({
                    title: "Cancel course?",
                    message: "Are you sure to cancel?",
                    buttons: {
                        cancel: {
                            label: '<i class="fa fa-times"></i> Cancel'
                        },
                        confirm: {
                            label: '<i class="fa fa-check"></i> Confirm'
                        }
                    },
                    callback: function (result) {
                        if (result) {
                            $.ajax({
                                url: "/api/courses/" + link.attr("data-course-id"), method: "DELETE"
                            })
                                .done(function () {
                                    link.parents("li").fadeOut(function () {
                                        $(this).remove();
                                    });
                                })
                                .fail(function () {
                                    alert("Something failed!");
                                });
                        }
                    }
                });
            });
        });
    </script>
}